<?php
require_once __DIR__ . '/../src/settings.php';

echo "Content-Type: text/html; charset=utf-8\n\n";
?>
<!DOCTYPE html>
<html>
<head>
    <title>URL Debug Test</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        .test { margin: 10px 0; padding: 10px; border: 1px solid #ddd; }
        .url { font-family: monospace; background: #f5f5f5; padding: 5px; }
        .error { color: red; }
        .success { color: green; }
    </style>
</head>
<body>
    <h1>URL Generation Debug Test</h1>
    
    <div class="test">
        <h3>Settings Configuration:</h3>
        <p><strong>Root:</strong> <?= settings()['root'] ?></p>
        <p><strong>Admin Page:</strong> <?= settings()['adminpage'] ?></p>
        <p><strong>Homepage:</strong> <?= settings()['homepage'] ?></p>
    </div>
    
    <div class="test">
        <h3>Generated URLs from header.php:</h3>
        <p><strong>Styles CSS:</strong> <span class="url"><?= settings()['adminpage'] ?>assets/css/styles.css</span></p>
        <p><strong>Notifications JS:</strong> <span class="url"><?= settings()['adminpage'] ?>assets/js/notifications.js</span></p>
    </div>
    
    <div class="test">
        <h3>URL Accessibility Test:</h3>
        <div id="url-test-results">Testing URLs...</div>
    </div>
    
    <div class="test">
        <h3>Browser Console Check:</h3>
        <p>Open Developer Tools (F12) and check the Console tab for 404 errors.</p>
        <p>Also check the Network tab for failed requests.</p>
    </div>
    
    <script>
        console.log('=== URL DEBUG TEST ===');
        
        // Test the exact URLs that are generated by PHP
        var urlsToTest = [
            '<?= settings()['adminpage'] ?>assets/css/styles.css',
            '<?= settings()['adminpage'] ?>assets/js/notifications.js',
            'assets/css/styles.css',
            'assets/js/scripts.js',
            'assets/js/notifications.js',
            'favicon.ico',
            '../favicon.ico',
            'discounts-management.php',
            'js/scripts.js', // old path that might still be referenced
            'css/styles.css' // old path that might still be referenced
        ];
        
        var results = document.getElementById('url-test-results');
        results.innerHTML = '';
        
        urlsToTest.forEach(function(url) {
            fetch(url)
                .then(response => {
                    var statusClass = response.status === 200 ? 'success' : 'error';
                    var statusText = response.status === 200 ? '✅ OK' : '❌ FAILED';
                    
                    if (response.status === 404) {
                        console.error('❌ 404 ERROR: ' + url);
                        statusText = '❌ 404 NOT FOUND';
                    } else if (response.status === 302) {
                        statusText = '🔄 REDIRECT';
                    }
                    
                    results.innerHTML += '<p class="' + statusClass + '">' + statusText + ' - <span class="url">' + url + '</span></p>';
                    console.log(statusText + ': ' + url);
                })
                .catch(error => {
                    results.innerHTML += '<p class="error">❌ ERROR - <span class="url">' + url + '</span> - ' + error.message + '</p>';
                    console.error('❌ FETCH ERROR: ' + url, error);
                });
        });
        
        // Also test for common missing resources that browsers automatically request
        var commonResources = [
            '/favicon.ico',
            '/apple-touch-icon.png',
            '/apple-touch-icon-precomposed.png'
        ];
        
        console.log('=== TESTING COMMON BROWSER RESOURCES ===');
        commonResources.forEach(function(resource) {
            fetch(resource)
                .then(response => {
                    if (response.status === 404) {
                        console.warn('❌ Common resource 404: ' + resource);
                    } else {
                        console.log('✅ Common resource OK: ' + resource);
                    }
                })
                .catch(error => {
                    console.warn('❌ Common resource error: ' + resource, error);
                });
        });
    </script>
</body>
</html>
